### ISSUE TITLE
[JGLOBUS-12] No private key loaded

### ISSUE THREAD

**Issue by bingzhang** [jglobus/JGlobus#170]
Hello:

I setup simpleCA from GT 6.0 toolkit. After I get x509 proxy certificate, I try to generate GSSCredential cred using jglobus:
```
            String x509 = "/tmp/x509up_u1000";
	    String proxyCertContent = new String(Files.readAllBytes(Paths.get(x509)), "UTF-8");
	    
	    byte[] proxyCertContentArray = proxyCertContent.getBytes();
	    ExtendedGSSManager gssm = (ExtendedGSSManager) ExtendedGSSManager
	        .getInstance();
	    GSSCredential cred = gssm.createCredential(proxyCertContentArray,
	        ExtendedGSSCredential.IMPEXP_OPAQUE,
	        GSSCredential.DEFAULT_LIFETIME, null,
	        GSSCredential.INITIATE_AND_ACCEPT);
```
Unfortunately, the code throws Exceptino:

```
Exception in thread "main" Defective credential detected. Caused by org.globus.gsi.GlobusCredentialException: [JGLOBUS-12] No private key loaded
	at org.globus.gsi.GlobusCredential.load(GlobusCredential.java:245)
	at org.globus.gsi.GlobusCredential.<init>(GlobusCredential.java:180)
	at org.globus.gsi.gssapi.GlobusGSSManagerImpl.createCredential(GlobusGSSManagerImpl.java:243)
```
It seems jgloubs failed to get key at:
https://github.com/dCache/jglobus-1.8/blob/master/src/org/globus/gsi/GlobusCredential.java#L210

**Comment by bingzhang** [comment]
never mind. I use different jglobus libs. I am going to close this one.
